  
spring:
  application:
    name: TestHarness   
  
server:
  port: 8282
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/