info:
  build:
    artifact : @project.artifactId@
    name: @project.name@ 
    description: Eureka Service Registry
    version: @project.version@
    
spring:
  application:
    name: JavaService  
  
server:
  port: 8181
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/