sidecar:
  port: 8000
  health-uri: http://localhost:8000/health
  
spring:
  application:
    name: PythonSidecar   
  
server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/