info:
  build:
    artifact : JavaService
    name: JavaService 
    description: Eureka Service Registry
    version: 0.0.1-SNAPSHOT
    
spring:
  application:
    name: JavaService  
  
server:
  port: 8181
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/